theme: jekyll-theme-minimal
title: Ismael's Portfolio
description: My Name Ismael Gonzalez, here is my portfolio to Programming 1
logo: https://avatars1.githubusercontent.com/u/118404664?s=400&u=a0d53603701c1307526eae4796a02c45ad4407cf&v=4
